### ISSUE TITLE
Code Suggestion

### ISSUE THREAD

**Issue by AntonioXIII** [NoahConnors/Amarelion-A-text-based-adventure-game-0.0.01-#4]
On line 26 of PlayerCharacter.java you have a method that sets a variable (didSpareLastEnemy) based on what was passed into the method. In your 'if statement' you set the value of didSpareLastEnemy to true if the passed in value was true, otherwise you set it to false if the value passed in was false.

You don't need the if statement, since all  you're really doing is setting the value of didSpareLastEnemy to whatever boolean value was passed in. So all you should really need in that method is:
`didSpareLastEnemy = enteredBool;`

Was just looking through your code and noticed that, I know your program is very early in development so there will be lots of different things, but just thought I'd point that out. Good luck!

**Comment by NoahConnors** [comment]
Thanks for the suggestion, really helps to know someone found this! Like I said, I am pretty new to this, and it really helps to have suggestions.

**Comment by AntonioXIII** [comment]
No problem! I'll be keeping an eye on the project, I like the story concept so I hope you keep moving forward with it.

**Comment by NoahConnors** [comment]
That means a lot Antonio, thanks!
