### ISSUE TITLE
IMPORTANT ANNOUNCEMENT

### ISSUE THREAD

**Issue by NoahConnors** [NoahConnors/Amarelion-A-text-based-adventure-game-0.0.01-#5]
Recently, I have been experimenting with the idea of adding graphics to the game, and now I think it might be possible. Using an application called GameMaker Studio, I have made a test title screen with self-composed music. I will be posting this on the GitHub page as an executable, just use the arrow keys to navigate the menu and enter to select. This is a huge change and I want to see if you guys like it or if you want to stick to the text-based java stuff. Please respond to this issue with your thoughts. 
-Noah Connors

**Comment by AntonioXIII** [comment]
First off: **VERY** cool main menu!

As far as which one you go with (whether you continue with the text based game, or the GameMaker Studio version), it really depends on you (and your other partner that's helping you with this). As I see it, there are some advantages and disadvantages to both:

## Text-Based Game
### Advantages
There's no better way to learn programming than to program. From what I've seen of GameMaker studio, they user their own language (GML). There's nothing wrong with that, but if you want to get into game development you might be better off learning a language that you could use in other environments. For example, if you learned C#, you can use that in Unity, or your own game engine. If you continued with Java, it wouldn't be very hard for you to take the concepts you learned using Java to other more popular game languages, like C#, or C++. GML is only used with GameMaker.

### Disadvantages
There's a lot more work involved for something that doesn't look as cool as what you could make in GameMaker. It would still be a cool game, but naturally a text based game just wouldn't look as good as well-made graphics.

## GameMaker Studio
### Advantages
You can probably do a lot more in GameMaker in a shorter amount of time than you could with the Java version. With your Java version, you have to be a lot more concerned about implementing EVERYTHING whereas in GameMaker a lot has been already implemented for you, or it's easier to implement than it would be in Java (or any other similar language). Additionally, with GameMaker, you may be able to learn the overarching concepts of programming without having to worry too much implementing those concepts with complex code. And you'll have a cool looking game to boot if you have the art skills!

### Disadvantages
I already mentioned how GML (Game Maker Studio's language) is only applicable to Game Maker Studio. And really, that's the only disadvantage I have off of the top of my head.

So, depends on what kind of learning experience you're looking for, and how 'new' you really are to this programming thing. GameMaker might do a nicer job of easing you into programming, but continuing with Java will give you a more complete learning experience.

**Comment by NoahConnors** [comment]
Again, it really helps to have an outside opinion that knows how to code (as my partner, Robby, is the writer, and doesn't know how to code). I am leaning towards GameMaker because there is just so much available right now to do. I haven't had the opportunity to discuss it with Robby yet, but I think he might be leaning the same way.

**Comment by AntonioXIII** [comment]
Sounds good then, and it seems like you've got a good start with the main menu already! Not to mention the music too. I look forward to trying out the project as it develops!
